import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

ThemeData orangeLight = ThemeData(
  fontFamily: GoogleFonts.openSans().fontFamily,
  colorScheme: const ColorScheme.light(
    primary: Color(0xff8f4c38),
    surfaceTint: Color(0xff8f4c38),
    onPrimary: Color(0xffffffff),
    primaryContainer: Color(0xffffdbd1),
    onPrimaryContainer: Color(0xff3a0b01),
    secondary: Color(0xff77574e),
    onSecondary: Color(0xffffffff),
    secondaryContainer: Color(0xffffdbd1),
    onSecondaryContainer: Color(0xff2c150f),
    tertiary: Color(0xff6c5d2f),
    onTertiary: Color(0xffffffff),
    tertiaryContainer: Color(0xfff5e1a7),
    onTertiaryContainer: Color(0xff231b00),
    error: Color(0xffba1a1a),
    onError: Color(0xffffffff),
    errorContainer: Color(0xffffdad6),
    onErrorContainer: Color(0xff410002),
    surface: Color(0xfffff8f6),
    onSurface: Color(0xff231917),
    onSurfaceVariant: Color(0xff53433f),
    outline: Color(0xff85736e),
    outlineVariant: Color(0xffd8c2bc),
    shadow: Color(0xff000000),
    scrim: Color(0xff000000),
    inverseSurface: Color(0xff392e2b),
    inversePrimary: Color(0xffffb5a0),
    primaryFixed: Color(0xffffdbd1),
    onPrimaryFixed: Color(0xff3a0b01),
    primaryFixedDim: Color(0xffffb5a0),
    onPrimaryFixedVariant: Color(0xff723523),
    secondaryFixed: Color(0xffffdbd1),
    onSecondaryFixed: Color(0xff2c150f),
    secondaryFixedDim: Color(0xffe7bdb2),
    onSecondaryFixedVariant: Color(0xff5d4037),
    tertiaryFixed: Color(0xfff5e1a7),
    onTertiaryFixed: Color(0xff231b00),
    tertiaryFixedDim: Color(0xffd8c58d),
    onTertiaryFixedVariant: Color(0xff534619),
    surfaceDim: Color(0xffe8d6d2),
    surfaceBright: Color(0xfffff8f6),
    surfaceContainerLowest: Color(0xffffffff),
    surfaceContainerLow: Color(0xfffff1ed),
    surfaceContainer: Color(0xfffceae5),
    surfaceContainerHigh: Color(0xfff7e4e0),
    surfaceContainerHighest: Color(0xfff1dfda),
  ),
);
